language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.4"
cache:
  directories:
    - $HOME/.m2
before_script:
  - psql -c 'create user "ese2017-full-integration" password '"'"'ese2017-full-integration'"'"' createdb;' -U postgres
  - psql -c 'create database "ese2017-full-integration"' -U ese2017-full-integration postgres
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: ese2017-full-integration
notifications:
  slack: $SLACK_API_KEY
